language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - addon-google_apis_x86-google-21
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services
  - sys-img-armeabi-v7a-android-21
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script: "./gradlew testDebugUnitTest"
branches:
- travisci
- development
notifications:
  hipchat:
    rooms:
      secure: pz0BnCGaSHP9/jtDmXSLOUu5F0Djy0IDTzOGbt2uNQ3EXproyuNQUCnmUCmQB/d8yiz7D/bCAuJNvYR6GVtjCmSQM11QVb+GIAgaAXLZ6FpAiSHvXjvqMolvryloknGsQTz7c25+huPFITToNW4o5dLnDj4i7Futz+KC0mOG0p+5HcGRNQ2WoMadRV1buNmj5rvxWLS/kxDRWXuOYw8jJ6TbhcCBupZm2C5Ma6C7CqQ59J6fnvuMNknwoj+Ox/waTkhPi5VhlOA7v2XtjRZSpGRAMBpMeiYmqvhGDK1daRoTNxki5tJUvy8t5RgchpdKWucqTBL4cvI3Dzs7jDJ5+qEpiaHugYIBMWDDxa5CH60tCVext8dASb3ddzYNZ6ZvKPwP5vG0kt0Vpm/uTFtFOKdLz/A8fkC+aBEwYs95cvVSY5bkXwwsOGtC9gmT7JELm2fe8yfYb6u3/IoO4PCp+MQ6I4So3nx0zoY7CzLndN1HwbWEbPVAABvOCSjpJQkrQ/1By8q/Ynsj77KflApBMkslTa8+rTpIAjwojcEbR0EyNuN/HCjLhIBlkYSzBnuC2rSSUIO3fTb0xqpfcrXmBkcLEUOxJvPz949dW8mT5rARQSksL0ehgO0C1QUhiZCYReyeRbj7nlazHQ4+ae3hLreT0hEXQthIOIxScf71Kuc=
    template:
    - 'Test run completed for %{repository}/<b>%{branch}</b>: <a href="%{build_url}">%{message}</a>
      Run duration: %{elapsed_time}'
    format: html
