language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - addon-google_apis_x86-google-21
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-21
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script: ./gradlew testDebugUnitTest
branches:
 - travisci
 - development
notifications:
  slack:
    rooms:
      secure: fBO6yW1muuxvopaCn5mvNC5OtcEaXIv/EMQr+VHlHI40JqgfDeqwezdGlqXP+XVw6MyKJ3eKEFu6Komgjz01DB7Hr9pyT3x/26mderFPV5FGj8Dftnj3E19kgoSAkONE4E/msU3Th8cQfSqGY74yYxZDnE0fnzbUaDit9KPJsWS4Jztc51gmCvFcov0pNIz2o5V45jNRd5XFwe/F8rBgmegr5grPl7D802hKzuI5WFvNvmtOSiS0+pMTE6PZRg2slo2u8PgC3zRx74Dt4vndg8XtwH9PQmJwwDsB2rIFOdvntPxoAwtzMUk1AvU8IMUmdZTYsPcf0rOQHjzrko+p6oz/ZoekDmzArc/OEcqmM1OvGWjI3FM+5pWS5Cnb9yP0/6d2tqsgEoTEz772sykVn0iZ0Fvyo73HlFIsq6USj8QEeU6xAG6TMb32Qez7dB9baXWxjVBj9QXVE4MTVzb5EBeB56lBmSpWV1/wVSYsQOdPRoObiK+B9YxahhZ0Y27hWQOHVIQ7ct22MzqriPB6ISN9kUmvNGAzktFINX4LtS6InzSzTqjwuWHMlToE+4B3KF4hQk426muvEhEYi2DJaiO2gGh5E7MR6mQt1vET190IZ8Y87tHZ6MuGdpP6/qEsAQxEFZUZhuWv18cfYpvXevWeZt5a8M5HseGe5RUQvb4=
    template:
    - 'Test run completed for %{repository}/*%{branch}*: <%{build_url}|%{message}> Run duration: %{elapsed_time}'
